language: python
python:
  - "3.6"
install:
  - pip install coverage
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - coverage run -m unittest discover .
after_success:
  - coverage report
  - coveralls
