language: python
python:
  - 3.6
branches:
  only:
    - master
install:
  - pip install coverage
  - pip install coveralls
  - pip install pycodestyle
  - pip install -r requirements.txt
script:
  - pycodestyle --max-line-length 119 pymlalgo
  - coverage run -m unittest discover pymlalgo
after_success:
  - coverage report
  - coveralls
